server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  cloud:
    gateway:
      server:
        webmvc:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          routes:
            - id: authorization-server
              uri: lb://AUTHORIZATION-SERVER
              predicates:
                - Path=/register,/oauth2/**,/login,/.well-known/**,/h2-console/**
              filters:
                - StripPrefix=0

            - id: ms-cotizaciones
              uri: lb://MS-COTIZACIONES
              predicates:
                - Path=/api/public/cotizaciones-vehiculos/**
              filters:
                - StripPrefix=0

            - id: ms-comercial
              uri: lb://MS-COMERCIAL
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/